# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "66b4b6eb-1be6-4433-b64f-77a7a00405a0"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # cocoapods

  # build your iOS app
  gym(
    scheme: "Stats",
    export_method: "app-store",
    include_bitcode: false
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end
