//
//  Keys.swift
//  Stats
//
//  Created by Parker Rushton on 3/27/17.
//  Copyright © 2017 AppsByPJ. All rights reserved.
//

import Foundation

let avatarKey = "avatar"
let avatarsKey = "avatars"
let calendarIdKey = "calendarId"
let currentSeasonIdKey = "currentSeasonId"
let creationDateKey = "creationDate"
let dateKey = "date"
let durationKey = "duration"
let emailKey = "email"
let fanTeamIdsKey = "fanTeamIds"
let gameIdKey = "gameId"
let genderKey = "gender"
let iCloudIdKey = "iCloudId"
let idKey = "id"
let inningKey = "inning"
let isCompletedKey = "isCompleted"
let isHomeKey = "isHome"
let isSeasonKey = "isSeason"
let imageKey = "image"
let imageURLStringKey = "imageURLString"
let isRegularSeasonKey = "isRegularSeason"
let isSubKey = "isSub"
let jerseyNumberKey = "jerseyNumber"
let lineupKey = "lineup"
let locationKey = "location"
let managedTeamIdsKey = "managedTeamIds"
let nameKey = "name"
let opponentKey = "opponent"
let opponentScoreKey = "opponentScore"
let orderKey = "order"
let outsKey = "outs"
let ownedTeamIdsKey = "ownedTeamIds"
let phoneKey = "phone"
let playerIdKey = "playerId"
let rbisKey = "rbis"
let recentTeamIdKey = "recentTeamId"
let resultCodeKey = "resultCode"
let scoreKey = "score"
let seasonId = "seasonId"
let seasonIdKey = "seasonId"
let seasonsKey = "seasons"
let shareCodeKey = "shareCode"
let sourceKey = "source"
let sportKey = "sport"
let statsKey = "stats"
let teamIdKey = "teamId"
let textKey = "text"
let usernameKey = "username"

// Refs
let atBatsRefKey = "atBats"
let gamesRefKey = "games"
let playersRefKey = "players"
let seasonsRefKey = "seasons"
let stockKey = "stock"
let teamsRefKey = "teams"
let usersRefKey = "users"
