//
//        .........     .........
//      ......  ...........  .....
//      ...        .....       ....
//     ...         ....         ...
//     ...       ........        ...
//     ....      .... ....      ...
//      ...      .... ....      ...
//      .....     .......     ....
//        ...      .....     ....
//         ....             ....
//           ....         ....
//            .....     .....
//              .....  ....
//                .......
//                  ...

import UIKit

final class LoadingImageViewController: UIViewController, AutoStoryboardInitializable {
    
    @IBOutlet weak var atLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        atLabel.rotate()
    }
    
}
